### ISSUE TITLE
Include tests for LinkedList using custom objects.

### ISSUE THREAD

**Issue by SinghKaranbir** [fsareshwala/cs404.1#26]
Hi Professor,

I recently noticed while doing Program 4, that my LinkedList implementation won't work on custom objects because I used '==' instead of equals(), but all test cases of Linked list passed. I am thinking of adding such test cases to the implementation

What do you think?

**Comment by fsareshwala** [comment]
That might be useful. How would you detect that code is using `==` instead of `.equals()`?

**Comment by SinghKaranbir** [comment]
I plan to create a custom class Point and use it in tests like LinkedList<Point>, by overriding equals and hashcode method, I can make sure that student has used equals() in the implementation of remove etc API of linkedlist. if thats not the case, tests will fail that are associated with custom objects. 

As we are using LinkedList implementation in later programs where we need to use it on custom objects. I think it will be helpful to ensure LinkedList API works on custom objects in the first Program itself. Let me know whats your thought on it :)

**Comment by fsareshwala** [comment]
Sounds good. Let's add that in. We can create the custom class in the `LinkedList_T.java` test code itself and have it used in a test function to ensure that `.equals()` is being used. Feel free to throw up a pull request.

**Comment by SinghKaranbir** [comment]
Thanks, I will do it by tomorrow :)

**Comment by fsareshwala** [comment]
Sounds good. No rush :).

**Comment by SinghKaranbir** [comment]
https://github.com/fsareshwala/cs404.1/pull/27
